# Generated by Django 4.2.6 on 2023-11-14 02:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_tasks', '0004_usuario_preguntasrespondidas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='QuizUsuario',
        ),
    ]
