# Generated by Django 4.2.6 on 2023-11-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_tasks', '0005_rename_usuario_quizusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='quizUser',
        ),
    ]
