# Generated by Django 4.2.6 on 2023-11-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_tasks', '0008_alter_preguntasrespondidas_quizuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_tasks.elegirrespuesta'),
        ),
    ]
